### ISSUE TITLE
Expose resetLocalStateForTests() for use in user tests

### ISSUE THREAD

**Issue by dfourie** [Light-Keeper/react-singleton-hook#375]
I am using react-singleton-hook for some fairly complex behaviour and would like to have some jest tests. Unfortunately the global nature of the hook makes having multiple tests for it impossible. 

When I have more than one test with the hook in it, I get this warning
"SingletonHooksContainer is mounted second time. You should mount SingletonHooksContainer before any other component and never unmount it.Alternatively, dont use SingletonHooksContainer it at all, we will handle that for you."

The second test also fails. Each test passes independently, so I suspect this global state is causing the problem.

In the tests for the container there is a function called resetLocalStateForTests that resets this global state that gets run after each test.  Exposing this function for users of the hook would solve the problem as I would be able to run it after each test.

**Comment by Dobby89** [comment]
@dfourie Why did you close this issue? Did you find a way around the issue without **resetLocalStateForTests**?
