### ISSUE TITLE
Use of the dark/light mode example causes react app to freeze

### ISSUE THREAD

**Issue by timsoulm** [Light-Keeper/react-singleton-hook#434]
I'm attempting to use the dark/light mode example in my react app exactly how it is written in the examples: https://github.com/Light-Keeper/react-singleton-hook#darklight-mode-switch

If there is at least one reference in a react component to useDarkMode, then calling setDarkMode will cause the app to freeze. I'm not sure if its due to issues with this module or something else. I've tried versions 3.2.1 and then the latest 3.2.3

**Comment by Light-Keeper** [comment]
@timsoulm, could you please provide a minimal repository with a complete reproducible example? the issue might be a mixture of your react, react-dom, and bundler settings.

**Comment by timsoulm** [comment]
I've moved over to using Saga in the project which seems to work better for my usecase at the moment. Feel free to close this out.
