### ISSUE TITLE
How to pass arguments to react-singleton-hook?

### ISSUE THREAD

**Issue by fmartins-andre** [Light-Keeper/react-singleton-hook#518]
Newbie question: Sometimes I need a hook that receive arguments in its declaration, something like:

```
const whatever = useMyCustomHook(withMyArgument)
```

How can I do it with react-singleton-hook?

I'm using version 3.4.0

**Comment by vadikoom** [comment]
Hi @fmartins-andre, the library is not designed for such use cases. If there were an ability to pass an argument, different consumers might pass other arguments, forcing the singleton hook to behave like it has different parameters simultaneously. 

Depending on your use case you need one of the following (or combination): 

#### If your arguments will be identical in all components that consume the hook 

```js
const useMyHookThatAcceptParams = (arg) => {
 /* impl using arg  */
}

// useMyCustomHook might be wrapped into singleton hook
const useMyCustomHook = () => {
   const arg = useMyData(); /* or any other way to obtain your singleton data */
   return useMyHookThatAcceptParams(arg)
}
```

#### If your arguments will be different in different components, but a shared singleton state backs the behavior of the hook 

```js 

const useMyCustomHook = (arg) => {

// useMySingletonHookThatReturnsDataAndCallbacks is wrapped into a singleton 
const { data,  callbacks } = useMySingletonHookThatReturnsDataAndCallbacks();

useEffect(() => {
// call some callbacks if data must be updated based arg. keep in mind that this hook might be used by many components
}, [arg, callbacks]) 


return someCalculations(data, arg);
}

```

I hope it helps. And will be happy to have a dicsusson if you see a way to improve API to support your case better.

**Comment by fmartins-andre** [comment]
Awesome! Thank you, @Light-Keeper.
